---
Name: cookieconsent
---
Broarm\CookieConsent\CookieConsent:
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
    #Analytics
    #Marketing
    #Preferences

Director:
  rules:
    acceptAllCookies: Page_Controller

ContentController:
  extensions:
    - Broarm\CookieConsent\ContentControllerExtension

SiteConfig:
  extensions:
    - Broarm\CookieConsent\SiteConfigExtension
