---
Name: cookieconsent
---
Broarm\CookieConsent\CookieConsent:
  include_javascript: true
  include_css: true
  create_default_pages: true
  cookies:
    Necessary:
      - CookieConsent

ContentController:
  extensions:
    - Broarm\CookieConsent\ContentControllerExtension

SiteConfig:
  extensions:
    - Broarm\CookieConsent\SiteConfigExtension
