---
Name: cookie-consent--config
---
CookieConsent:
  disable_cookie_consent: false
  disable_iframe_manager: false
  disable_default_css: false
  disable_default_js: false
  enable_google_consent_mode: false
  enable_consent_logging: true
  external_media_category: 'embeds'
  cookie_registry_path: 'cookie-consent/cookie-registry/open-cookie-database.json'
  gui_options:
    consentModal:
      layout: 'cloud'
      position: 'bottom'
  categories:
    functional:
      enabled: true
      readOnly: true
      cookies:
        PHPSESSID:
          description: 'Preserves user session state across page requests.'
          expiration: 'Session'
        cc_cookie:
          description: "Stores the user's cookie preferences for this domain."
          expiration: '1 year'
    personalization:
      enabled: false
    analytics:
      enabled: false
    marketing:
      enabled: false
    embeds:
      enabled: false
  external_media_services:
    - youtube
    - vimeo
    - googlemaps
