---
Name: cookie-consent--config
---
CookieConsent:
  disable_cookie_consent: false
  disable_default_css: false
  disable_default_js: false
  enable_google_consent_mode: false
  enable_consent_logging: true
  enable_external_media_management: true
  external_media_category: 'embeds'
  cookie_registry_path: 'cookie-consent/open-cookie-database.json'
  clear_cookies_on_cookie_registry_update: true
  gui_options:
    consentModal:
      layout: 'cloud'
      position: 'bottom'
  categories:
    functional:
      enabled: true
      readOnly: true
      cookies:
        - cc_cookie
    personalization:
      enabled: false
    analytics:
      enabled: false
    marketing:
      enabled: false
    embeds:
      enabled: false
  external_media_services:
    - youtube
    - vimeo
    - googlemaps
