---
Name: cookieconsent
---
Broarm\CookieConsent\CookieConsent:
  include_javascript: true
  include_css: true
  create_default_pages: true
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
    #Analytics
    #Marketing
    #Preferences

SilverStripe\Control\Director:
  rules:
    acceptAllCookies: Page_Controller

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Broarm\CookieConsent\ContentControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Broarm\CookieConsent\SiteConfigExtension
